version: '3.4'


services:
  mongo:
    image: 127.0.0.1:5000/mongo
    deploy:
      replicas: 3
    networks:
      - nexus_app
    secrets:
      - mongo-keyfile
      - mongo-admin-pwd

  mongoc:
    image: 127.0.0.1:5000/mongoc
    depends_on:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SERVICE_NAME=nexus_mongo
    networks:
      - nexus_app
    secrets:
      - mongo-admin-pwd
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  redis:
    image: 127.0.0.1:5000/redis
    deploy:
      replicas: 1
    networks:
      - nexus_app

  app:
    image: 127.0.0.1:5000/nexus-stats
    depends_on:
      - mongo
      - mongoc
      - redis
    deploy:
      replicas: 1
    networks:
      - nexus_app
    secrets:
      - mongo-admin-pwd
      - nexus-private-key
      - nexus-public-key


networks:
  nexus_app:
    external: true


secrets:
  mongo-keyfile:
    external: true

  mongo-admin-pwd:
    external: true

  nexus-private-key:
    external: true

  nexus-public-key:
    external: true