version: '3.4'


services:
  mongo:
    image: 127.0.0.1:5000/mongo
    deploy:
      replicas: 3
    networks:
      - nexus_app
    secrets:
      - mongo-keyfile
      - mongo-admin-pwd

  mongoc:
    image: 127.0.0.1:5000/mongoc
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SERVICE_NAME=nexus_mongo
    networks:
      - nexus_app
    secrets:
      - mongo-admin-pwd
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock


networks:
  nexus_app:
    external: true


secrets:
  mongo-keyfile:
    external: true

  mongo-admin-pwd:
    external: true