version: '3.4'


services:
  traefik:
    image: traefik:alpine
    command: --logLevel=DEBUG
    deploy:
      placement:
        constraints:
          - node.role == manager
          - engine.labels.mongo != true
      update_config:
        delay: 10s
      labels:
        - traefik.port=8080
        - traefik.backend.loadbalancer.method=drr
        - traefik.frontend.rule=Host:status.nexushub.co
        - traefik.frontend.entryPoints=http,https
        - traefik.backend=traefik
    networks:
      - app
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - nexus_certs:/certs
      - //var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/services/traefik/config.toml:/etc/traefik/traefik.toml

  certbot:
    image: 127.0.0.1:5000/certbot
    deploy:
      placement:
        constraints:
          - node.role == manager
          - engine.labels.mongo != true
      update_config:
        delay: 10s
    networks:
      - app
    volumes:
      - nexus_certs:/etc/letsencrypt
    secrets:
      - nexus-cloudflare-token

  bosun:
    image: 127.0.0.1:5000/bosun
    environment:
      - DEPLOY_BRANCH=production
    deploy:
      placement:
        constraints:
          - node.role == manager
          - engine.labels.mongo != true
      update_config:
        delay: 10s
      labels:
        - traefik.port=5000
        - traefik.backend.loadbalancer.method=drr
        - traefik.frontend.rule=Host:cd.nexushub.co;Path:/deploy
        - traefik.frontend.entryPoints=http,https
        - traefik.backend=bosun
    networks:
      - app
    secrets:
      - nexus-dockerhub-token
    volumes:
      - /opt/docker/compose:/compose
      - //var/run/docker.sock:/var/run/docker.sock

  #
  # API nodes
  #
  api:
    image: 127.0.0.1:5000/nexus-stats
    deploy:
      replicas: 2
      update_config:
        delay: 10s
      placement:
        constraints:
          - engine.labels.mongo != true
      labels:
        - traefik.port=3003
        - traefik.backend.loadbalancer.method=drr
        - traefik.frontend.rule=Host:api.nexushub.co
        - traefik.frontend.entryPoints=http,https
        - traefik.backend=api
    networks:
      - app
    secrets:
      - nexus-public-key
      - mongo-admin-pwd
      - nexus-warframe-bot-key
      - nexus-warframe-bot-secret
      - tsm-api-key
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=api

  auth:
    image: 127.0.0.1:5000/nexus-stats
    deploy:
      replicas: 2
      update_config:
        delay: 10s
      placement:
        constraints:
          - engine.labels.mongo != true
      labels:
        - traefik.port=3030
        - traefik.backend.loadbalancer.method=drr
        - traefik.frontend.rule=Host:auth.nexushub.co
        - traefik.frontend.entryPoints=http,https
        - traefik.backend=auth
    networks:
      - app
    secrets:
      - nexus-public-key
      - nexus-private-key
      - mongo-admin-pwd
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=auth

  ui:
    image: 127.0.0.1:5000/nexus-stats
    deploy:
      replicas: 2
      update_config:
        delay: 10s
      placement:
        constraints:
          - engine.labels.mongo != true
      labels:
        - traefik.port=3000
        - traefik.backend.loadbalancer.method=drr
        - traefik.frontend.rule=Host:nexushub.co
        - traefik.frontend.entryPoints=http,https
        - traefik.backend=ui
    networks:
      - app
    secrets:
      - nexus-public-key
      - mongo-admin-pwd
      - nexus-cubic-key
      - nexus-cubic-secret
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=ui


secrets:
  nexus-dockerhub-token:
    external: true

  nexus-cloudflare-token:
    external: true

  nexus-ga-key:
    external: true

  nexus-cubic-key:
    external: true
  nexus-cubic-secret:
    external: true

  nexus-warframe-bot-key:
    external: true
  nexus-warframe-bot-secret:
    external: true

  tsm-api-key:
    external: true


volumes:
  nexus_certs:
