version: '3.4'


services:
  mongo:
    image: 127.0.0.1:5000/mongo
    deploy:
      replicas: 3
    networks:
      - app
    secrets:
      - mongo-keyfile
      - mongo-admin-pwd
    volumes:
      - mongo_backup:/data/backups

  mongoc:
    image: 127.0.0.1:5000/mongoc
    depends_on:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SERVICE_NAME=nexus_mongo
    networks:
      - app
    secrets:
      - mongo-admin-pwd
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  redis:
    image: 127.0.0.1:5000/redis
    deploy:
      replicas: 1
    networks:
      - app

networks:
  app:


secrets:
  mongo-keyfile:
    external: true

  mongo-admin-pwd:
    external: true

  nexus-private-key:
    external: true

  nexus-public-key:
    external: true

  tsm-client-id:
    external: true

  tsm-client-secret:
    external: true


volumes:
  mongo_backup:
