version: '3.4'

services:
  traefik:
    image: traefik:alpine
    deploy:
      labels:
        - traefik.frontend.rule=Host:status.staging.nexushub.co

  bosun:
    image: 127.0.0.1/bosun
    environment:
      - DEPLOY_BRANCH=staging
    deploy:
      labels:
        - traefik.frontend.rule=Host:cd.staging.nexushub.co

  #
  # API nodes
  #
  api:
    image: 127.0.0.1/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:api.staging.nexushub.co

  auth:
    image: 127.0.0.1/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:auth.staging.nexushub.co

  ui:
    image: 127.0.0.1/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:staging.nexushub.co
