networks:
  nexus_app:
    external: true
secrets:
  mongo-admin-pwd:
    external: true
  mongo-keyfile:
    external: true
  nexus-auth-key:
    external: true
  nexus-auth-secret:
    external: true
  nexus-cert-private:
    external: true
  nexus-cert-public:
    external: true
  nexus-main-key:
    external: true
  nexus-main-secret:
    external: true
  nexus-private-key:
    external: true
  nexus-public-key:
    external: true
  nexus-ui-key:
    external: true
  nexus-ui-secret:
    external: true
  nexus-warframe-key:
    external: true
  nexus-warframe-secret:
    external: true
services:
  auth_api:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: auth-api
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    ports:
    - published: 3030
      target: 3030
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-auth-key
    - source: nexus-auth-secret
    - source: nexus-private-key
    - source: nexus-public-key
  auth_core:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: auth-core
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-auth-key
    - source: nexus-auth-secret
    - source: nexus-private-key
    - source: nexus-public-key
  main_api:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: main-api
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    ports:
    - published: 3003
      target: 3003
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-main-key
    - source: nexus-main-secret
    - source: nexus-public-key
  main_core:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: main-core
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-main-key
    - source: nexus-main-secret
    - source: nexus-public-key
  mongo:
    deploy:
      replicas: 3
    image: 127.0.0.1:5000/mongo
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    - source: mongo-keyfile
    volumes:
    - mongo_backup:/data/backups:rw
  mongoc:
    depends_on:
    - mongo
    deploy:
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    environment:
      SERVICE_NAME: nexus_mongo
    image: 127.0.0.1:5000/mongoc
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock:rw
  nginx:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    image: 127.0.0.1:5000/nginx
    networks:
      nexus_app: null
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    secrets:
    - source: nexus-cert-private
    - source: nexus-cert-public
  redis:
    deploy:
      replicas: 1
    image: 127.0.0.1:5000/redis
    networks:
      nexus_app: null
  ui_api:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: ui-api
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    ports:
    - published: 3000
      target: 3000
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-public-key
    - source: nexus-ui-key
    - source: nexus-ui-secret
  ui_core:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: ui-core
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-public-key
    - source: nexus-ui-key
    - source: nexus-ui-secret
  warframe_core:
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
    environment:
      DOCKER: "true"
      NEXUS_TARGET_NODE: warframe-core
      NODE_ENV: production
    image: 127.0.0.1:5000/nexus-stats:staging
    networks:
      nexus_app: null
    secrets:
    - source: mongo-admin-pwd
    - source: nexus-public-key
    - source: nexus-warframe-key
    - source: nexus-warframe-secret
version: '3.4'
volumes:
  mongo_backup: {}

