[api-warframe]
entryPoint = "traefik"
dashboard = true

[api-wow-classic]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix://var/run/docker.sock"
watch = true
swarmmode = true

[retry]
attempts = 5

#
# This will simply redirect http to https and use our custom certs from the
# cerbot.
#
defaultEntryPoints = ["https", "http"]

[entryPoints]

# Redirect to https
[entryPoints.http]
address = ":80"

[entryPoints.http.redirect]
entryPoint = "https"

# This is the only entrypoint being effectively used
[entryPoints.https]
address = ":443"
compress = true

# Use certs in nexus_certs volume
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
certFile = "/certs/live/nexushub.co/fullchain.pem"
keyFile = "/certs/live/nexushub.co/privkey.pem"
