# Enable API
[api]
dashboard = true

# Enable docker provider
[providers.docker]
endpoint = "unix://var/run/docker.sock"
swarmMode = true

# EntryPoints
[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.https]
address = ":443"

# TLS config
[[tls.certificates]]
certFile = "/certs/live/nexushub.co/fullchain.pem"
keyFile = "/certs/live/nexushub.co/privkey.pem"

# Enable debug logs
[log]
level = "DEBUG"
