version: '3.4'


services:
  nginx:
    image: nexusstats/nginx
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    ports:
      - 80:80
      - 443:443
    secrets:
      - nexus-cert-public
      - nexus-cert-private

  update:
    image: nexusstats/update
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-dockerhub-token
    ports:
      - 5000:5000

  # API nodes
  main_api:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
      - mongo-admin-pwd
      - nexus-main-key
      - nexus-main-secret
    ports:
      - 3003:3003
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=main-api

  auth_api:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
      - nexus-private-key
      - nexus-auth-key
      - nexus-auth-secret
      - mongo-admin-pwd
    ports:
      - 3030:3030
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=auth-api

  ui_api:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
      - mongo-admin-pwd
      - nexus-ui-key
      - nexus-ui-secret
    ports:
      - 3000:3000
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=ui-api


  # Core nodes
  main_core:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-main-key
      - nexus-main-secret
      - mongo-admin-pwd
      - nexus-public-key
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=main-core

  auth_core:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-auth-key
      - nexus-auth-secret
      - mongo-admin-pwd
      - nexus-private-key
      - nexus-public-key
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=auth-core

  ui_core:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-ui-key
      - nexus-ui-secret
      - mongo-admin-pwd
      - nexus-public-key
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=ui-core

  warframe_core:
    image: nexusstats/nexus-stats
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
    networks:
      - nexus_app
    secrets:
      - nexus-warframe-key
      - nexus-warframe-secret
      - mongo-admin-pwd
      - nexus-public-key
    environment:
      - DOCKER=true
      - NODE_ENV=production
      - NEXUS_TARGET_NODE=warframe-core


# Core credentials
secrets:
  nexus-dockerhub-token:
    external: true

  nexus-cert-public:
    external: true
  nexus-cert-private:
    external: true

  nexus-main-key:
    external: true
  nexus-main-secret:
    external: true

  nexus-warframe-key:
    external: true
  nexus-warframe-secret:
    external: true

  nexus-auth-key:
    external: true
  nexus-auth-secret:
    external: true

  nexus-ui-key:
    external: true
  nexus-ui-secret:
    external: true
