version: '3.4'


services:
  traefik:
    image: traefik:v2.1.2
    deploy:
      labels:
        - traefik.http.routers.traefik_api.rule=Host(`status.staging.nexushub.co`)

  bosun:
    image: nexusstats/bosun
    environment:
      - DEPLOY_BRANCH=staging
    deploy:
      labels:
        - traefik.http.routers.bosun.rule=Host(`cd.staging.nexushub.co`) && Path(`/deploy`)

  #
  # API nodes
  #
  api_warframe:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.http.routers.api-warframe.rule=Host(`api.staging.nexushub.co`)
#  api_wowclassic:
#    image: nexusstats/nexus-stats:staging
#    environment:
#      - NEXUS_STAGING=true
#    #      - NODE_DEBUG=true
#    #    volumes:
#    #      - /opt/debug:/app/nexushub
#    deploy:
#      replicas: 1
#      labels:
#        - traefik.http.routers.api-wowclassic.rule=Host(`api.staging.nexushub.co`) && PathPrefix(`/wow-classic`)

  auth:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.http.routers.auth.rule=Host(`auth.staging.nexushub.co`)

  ui:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.http.routers.ui.rule=Host(`staging.nexushub.co`, `wow-classic.staging.nexushub.co`)
        # WoW Classic redirect
        - traefik.http.middlewares.wowclassic-redirect.redirectregex.regex=^https://wow-classic\.staging\.nexushub\.co/(.*)
        - traefik.http.middlewares.wowclassic-redirect.redirectregex.replacement=https://staging.nexushub.co/wow-classic/$${1}
        - traefik.http.middlewares.wowclassic-redirect.redirectregex.permanent=true
        # Warframe redirect
        - traefik.http.middlewares.warframe-redirect.redirectregex.regex=^https://warframe\.staging\.nexushub\.co/(.*)
        - traefik.http.middlewares.warframe-redirect.redirectregex.replacement=https://staging.nexushub.co/warframe/$${1}
        - traefik.http.middlewares.warframe-redirect.redirectregex.permanent=true
  #
  # Services
  #
  warframe_clear:
    image: nexusstats/nexus-stats:staging

  warframe_opm:
    image: nexusstats/nexus-stats:staging

  warframe_wfm:
    image: nexusstats/nexus-stats:staging

  wowclassic_scans:
    image: nexusstats/nexus-stats:staging
