version: '3.4'

services:
  traefik:
    image: traefik:alpine
    deploy:
      labels:
        - traefik.frontend.rule=Host:status.staging.nexushub.co

  bosun:
    image: nexusstats/bosun
    environment:
      - DEPLOY_BRANCH=staging
    deploy:
      labels:
        - traefik.frontend.rule=Host:cd.staging.nexushub.co

  #
  # API nodes
  #
  main_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      labels:
        - traefik.frontend.rule=Host:api.staging.nexushub.co

  auth_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      labels:
        - traefik.frontend.rule=Host:auth.staging.nexushub.co

  ui_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
    deploy:
      labels:
        - traefik.frontend.rule=Host:staging.nexushub.co

  #
  # Core nodes
  #
  main_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats

  auth_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats

  ui_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats

  warframe_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexus-stats
