version: '3.4'


services:
  nginx:
    image: 127.0.0.1:5000/nginx
    networks:
      - nexus_app
    ports:
      - 80:80
      - 443:443

  # API nodes
  api_warframe:
    image: 127.0.0.1:5000/nexus-api-warframe
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
    ports:
      - 3000:3000

  api_auth:
    image: 127.0.0.1:5000/nexus-api-auth
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
      - nexus-private-key
      - nexus-core-auth-key
      - nexus-core-auth-secret
      - mongo-admin-pwd
    ports:
      - 3001:3000

  api_view:
    image: 127.0.0.1:5000/nexus-api-view
    networks:
      - nexus_app
    secrets:
      - nexus-public-key
    ports:
      - 3002:3000


  # Core nodes
  core_warframe:
    image: 127.0.0.1:5000/nexus-core-warframe
    networks:
      - nexus_app
    secrets:
      - nexus-core-warframe-key
      - nexus-core-warframe-secret
      - mongo-admin-pwd

  core_auth:
    image: 127.0.0.1:5000/nexus-core-auth
    networks:
      - nexus_app
    secrets:
      - nexus-core-auth-key
      - nexus-core-auth-secret
      - mongo-admin-pwd
      - nexus-private-key

  core_view:
    image: 127.0.0.1:5000/nexus-core-view
    networks:
      - nexus_app
    secrets:
      - nexus-core-view-key
      - nexus-core-view-secret
      - mongo-admin-pwd


# Core credentials
secrets:
  nexus-core-warframe-key:
    external: true
  nexus-core-warframe-secret:
    external: true

  nexus-core-auth-key:
    external: true
  nexus-core-auth-secret:
    external: true

  nexus-core-view-key:
    external: true
  nexus-core-view-secret:
    external: true
