version: '3.4'


services:
  traefik:
    image: traefik:alpine
    deploy:
      labels:
        - traefik.frontend.rule=Host:status.staging.nexushub.co

  bosun:
    image: nexusstats/bosun
    environment:
      - DEPLOY_BRANCH=staging
    deploy:
      labels:
        - traefik.frontend.rule=Host:cd.staging.nexushub.co

  #
  # API nodes
  #
  api_warframe:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:api.staging.nexushub.co
  api_wowclassic:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
    #      - NODE_DEBUG=true
    #    volumes:
    #      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:api.staging.nexushub.co;PathPrefix=/wow-classic

  auth:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:auth.staging.nexushub.co

  ui:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:staging.nexushub.co,wow-classic.staging.nexushub.co
        - traefik.frontend.redirect.regex=^https?://wow-classic.staging.nexushub.co/(.*)
        - traefik.frontend.redirect.replacement=https://staging.nexushub.co/wow-classic/$${1}

  #
  # Services
  #
  warframe_clear:
    image: nexusstats/nexus-stats:staging

  warframe_opm:
    image: nexusstats/nexus-stats:staging

  warframe_wfm:
    image: nexusstats/nexus-stats:staging

  wowclassic_scans:
    image: nexusstats/nexus-stats:staging
