version: '3.4'

services:
  bosun:
    image: nexusstats/bosun
    environment:
      - DEPLOY_BRANCH=staging

  # API nodes
  main_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules

  auth_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules

  ui_api:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules


  # Core nodes
  main_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules

  auth_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules

  ui_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules

  warframe_core:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug/node_modules:/app/nexus-stats/node_modules
