version: '3.4'


services:
  mongo:
    image: nexusstats/mongo:directoryperdb
    deploy:
      mode: global
      placement:
        constraints:
          - engine.labels.mongo == true
    networks:
      - app
    secrets:
      - mongo-keyfile
      - mongo-admin-pwd
    volumes:
      - mongo:/data/db
      - mongo_backup:/data/backups
    logging:
      options:
        max-file: 5
        max-size: 10m

  mongoc:
    image: nexusstats/mongoc
    depends_on:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SERVICE_NAME=nexus_mongo
    networks:
      - app
    secrets:
      - mongo-admin-pwd
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-file: 5
        max-size: 10m

  redis:
    image: nexusstats/redis
    deploy:
      replicas: 1
      placement:
        constraints:
          - engine.labels.mongo != true
    networks:
      - app
    logging:
      options:
        max-file: 5
        max-size: 10m


networks:
  app:


secrets:
  mongo-keyfile:
    external: true

  mongo-admin-pwd:
    external: true

  nexus-private-key:
    external: true

  nexus-public-key:
    external: true

  tsm-api-key:
    external: true


volumes:
  mongo:
  mongo_backup:
