version: '3.4'

services:
  # API nodes
  main_api:
    image: nexusstats/nexus-stats:staging

  auth_api:
    image: nexusstats/nexus-stats:staging

  ui_api:
    image: nexusstats/nexus-stats:staging


  # Core nodes
  main_core:
    image: nexusstats/nexus-stats:staging

  auth_core:
    image: nexusstats/nexus-stats:staging

  ui_core:
    image: nexusstats/nexus-stats:staging

  warframe_core:
    image: nexusstats/nexus-stats:staging
