version: '3.4'


services:
  mongo:
    image: nexusstats/mongo
    deploy:
      replicas: 3
    networks:
      - nexus_app
    secrets:
      - mongo-keyfile
      - mongo-admin-pwd
    volumes:
      - mongo_backup:/data/backups

  mongoc:
    image: nexusstats/mongoc
    depends_on:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - SERVICE_NAME=nexus_mongo
    networks:
      - nexus_app
    secrets:
      - mongo-admin-pwd
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  redis:
    image: nexusstats/redis
    deploy:
      replicas: 1
    networks:
      - nexus_app

  #portainer:
  #  image: portainer/portainer
  #  ports:
  #    - 9000:9000
  #  networks:
  #    - nexus_app
  #  command: -H unix:///var/run/docker.sock
  #  volumes:
  #    - //var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data


networks:
  nexus_app:
    external: true


secrets:
  mongo-keyfile:
    external: true

  mongo-admin-pwd:
    external: true

  nexus-private-key:
    external: true

  nexus-public-key:
    external: true


volumes:
  mongo_backup:
  portainer_data:
