version: '3.4'


services:
  dev:
    image: nexusstats/nexus-stats-dev
    volumes:
      - VOLUME PLACEHOLDER
    ports:
      - 3000:3000
      - 3003:3003
      - 3030:3030
    depends_on:
      - mongo
      - mongoc
      - redis
    deploy:
      replicas: 1
    networks:
      - app
    secrets:
      - mongo-admin-pwd
      - nexus-private-key
      - nexus-public-key
      - tsm-client-id
      - tsm-client-secret
    environment:
      - DOCKER=true
    tty: true
    stdin_open: false

  # Make mongo run without engine label
  mongo:
    deploy:
      placement:
        constraints: ""
