version: '3.4'


services:
  dev:
    image: 127.0.0.1:5000/nexus-stats-dev
    volumes:
      - VOLUME PLACEHOLDER
    ports:
      - 3010:3010
      - 3020:3020
      - 3030:3030
    depends_on:
      - mongo
      - mongoc
      - redis
    deploy:
      replicas: 1
    networks:
      - nexus_app
    secrets:
      - mongo-admin-pwd
      - nexus-private-key
      - nexus-public-key