version: '3.4'


services:
  traefik:
    image: traefik:alpine
    deploy:
      labels:
        - traefik.frontend.rule=Host:status.staging.nexushub.co

  bosun:
    image: nexusstats/bosun
    environment:
      - DEPLOY_BRANCH=staging
    deploy:
      labels:
        - traefik.frontend.rule=Host:cd.staging.nexushub.co

  #
  # API nodes
  #
  api:
    image: nexusstats/nexus-stats:staging
    secrets:
      - tsm-api-key
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:api.staging.nexushub.co

  auth:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:auth.staging.nexushub.co

  ui:
    image: nexusstats/nexus-stats:staging
    environment:
      - NEXUS_STAGING=true
#      - NODE_DEBUG=true
#    volumes:
#      - /opt/debug:/app/nexushub
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:staging.nexushub.co

  #
  # Services
  #
  warframe_clear:
    image: nexusstats/nexus-stats:staging

  warframe_opm:
    image: nexusstats/nexus-stats:staging

  warframe_wfm:
    image: nexusstats/nexus-stats:staging

  wowclassic_scans:
    image: nexusstats/nexus-stats:staging
    secrets:
      tsm-api-key


secrets:
  tsm-api-key:
    external: true
