networks:
  nexus_ci:
    external: true
secrets:
  nexus-cert-private:
    external: true
  nexus-cert-public:
    external: true
services:
  agent:
    command: agent
    environment:
      DRONE_SECRET: 4OcFHw7Twcb80DPbnofgZftfye9egRXhqQFPQKmX3Tb5NCnPqny1dzOmi53vBXHr
      DRONE_SERVER: server:9000
    image: drone/agent:alpine
    networks:
      nexus_ci: null
    volumes:
    - //var/run/docker.sock:/var/run/docker.sock:rw
  nginx:
    image: 127.0.0.1:5000/drone-nginx
    networks:
      nexus_ci: null
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    secrets:
    - source: nexus-cert-public
    - source: nexus-cert-private
  server:
    environment:
      DRONE_ADMIN: Kaptard,Nakroma
      DRONE_GITHUB: "true"
      DRONE_GITHUB_CLIENT: 3d33de70f0635c51c1c9
      DRONE_GITHUB_SECRET: a4252e6daad7b7ac9d92afd83b571567fe31633a
      DRONE_HOST: https://ci.nexus-stats.com
      DRONE_OPEN: "true"
      DRONE_ORGS: nexus-devs
      DRONE_SECRET: 4OcFHw7Twcb80DPbnofgZftfye9egRXhqQFPQKmX3Tb5NCnPqny1dzOmi53vBXHr
    image: drone/drone:alpine
    networks:
      nexus_ci: null
    volumes:
    - drone:/var/lib/drone:rw
version: '3.4'
volumes:
  drone: {}

